### ISSUE TITLE
Fix indentation

### ISSUE THREAD

**Issue by wdsrocha** [wesleysr/optimization#2]
There are few places where indentation is kinda off

For example, on line 25 - 27 of `genetic_algorithm/Main.cpp`

```c++
	for (int i = 0; i < MAX_ITER; i++)
	{
        std::cout << "Iteration " << i+1 << ":\n";
```

the expected code should be:

```c++
	for (int i = 0; i < MAX_ITER; i++)
	{
                std::cout << "Iteration " << i+1 << ":\n";
```

**Comment by UltimaBGD** [comment]
I can take a look at this.

**Comment by wdsrocha** [comment]
Ok @UltimaBGD, thanks!

I'll assign it to you.
